changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: Fixed Bugs
      labels:
        - bug
    - title: New Features
      labels:
        - 'new feature'
    - title: Enhancements
      labels:
        - enhancement
    - title: Translations
      labels:
        - lang
    - title: Refactoring
      labels:
        - refactor
    - title: Core Development
      labels:
        - coredev
    - title: Others (Only for checking. Remove this category)
      labels:
        - "*"
