site_name: SmartyURL Docs
docs_dir: docs
site_dir: site
repo_url: https://github.com/Extendy/SmartyURL
site_description: 'SmartyURL Documentation'
site_author: 'Extendy Team'
copyright: 'Copyrights © 2023 Extendy Team'
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Why Using SmartyURL?: why-smartyurl.md
  - Developer's Guide: developers.md
  - IP Geolocation: ip2location.md
  - License: license.md
  - Legal Notice: legalnotice.md
theme:
    name: material
    language: en
    direction: ltr
extra:
  version: v0.0.0-dev-dnd.2
  alternate:
    - name: عربي
      link: https://smartyurl.extendy.net/docs/ar/
      lang: ar
markdown_extensions:
  - admonition
